Config:
  run_readme: Increased number of timesteps
  N: 16
  dim: 2
  box_size: 10.0
  dt: 0.001
  num_steps: 20000
  train_fname: train_states.npz
  val_fname: val_states.npz
  seed_train: 0
  seed_val: 68
  mass: 1.0
  lr: 5.0e-05
  batch_size: 1000
  mask_ratio: 0.25
  ema_decay: 0.996
  num_epochs: 20
  save_every: 10
  load_epoch: 10
EGNNconfig:
  in_feat_dim: 4
  h_dim: 96
  msg_dim: 96
  hidden_dim: 192
  n_layers: 3
  mlp_depth: 2
  out_dim: 96
PredictorConfig:
  in_feat_dim: 96
  h_dim: 96
  msg_dim: 96
  hidden_dim: 192
  n_layers: 2
  mlp_depth: 2
  out_dim: 96
